name: 'Carpool Vote - Vote America'
description: 'Get a ride or share a ride to the polls. Every American DESERVES a vote!'

encoding: UTF-8

markdown: kramdown
highlighter: rouge

permalink: :title/
relative_permalinks: false

api: "https://api.carpoolvote.com/live"
cp_site: "http://carpoolvote.com"
webpack_bundle: "bundle-production"

exclude: ['node_modules']
